# https://github.com/actions
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties
      # https://github.com/gradle/actions
      - uses: gradle/actions/wrapper-validation@v4

      - run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: net.cactii.mathdoku-debug.apk
          path: app/build/outputs/apk/debug/net.cactii.mathdoku-debug.apk